apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plant-disease-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: plant-disease-api.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: plant-disease-service
            port:
              number: 80
